# Autogenerated by devscripts/update-version.py

__version__ = '2025.09.05'

RELEASE_GIT_HEAD = '8ed7f0c6103bcdf3e2ddca57eb3b868043fa7642'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'bashonly/yt-dlp'

_pkg_version = '2025.09.05'
