# Autogenerated by devscripts/update-version.py

__version__ = '2025.09.02'

RELEASE_GIT_HEAD = '7de7b11adb9b532790a84ee82a7dd87ea0dc6ffc'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'bashonly/yt-dlp'

_pkg_version = '2025.09.02'
