# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.06.234645'

RELEASE_GIT_HEAD = '6fef824025b3c2f0ca8af7ac9fa04b10d09a3591'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'bashonly/yt-dlp'

ORIGIN = 'bashonly/yt-dlp'

_pkg_version = '2024.12.06.234645'
