services:

  linux_x86_64:
    build:
      context: linux
      platforms:
        - "linux/amd64"
      args:
        BASEIMAGE: ghcr.io/yt-dlp/manylinux2014_x86_64-shared:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  linux_x86_64_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/amd64"
      args:
        IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
    environment:
      EXE_NAME: ${EXE_NAME}
    volumes:
      - ~/build:/build

  linux_aarch64:
    build:
      context: linux
      platforms:
        - "linux/arm64"
      args:
        BASEIMAGE: ghcr.io/yt-dlp/manylinux2014_aarch64-shared:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  linux_aarch64_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/arm64"
      args:
        IMAGE: quay.io/pypa/manylinux2014_aarch64:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      SKIP_UPDATE_TO: "1"  # TODO: remove when there is a glibc2.17 aarch64 release to --update-to
    volumes:
      - ~/build:/build

  linux_armv7l:
    build:
      context: linux
      platforms:
        - "linux/arm/v7"
      args:
        BASEIMAGE: ghcr.io/yt-dlp/manylinux_2_31_armv7l-shared:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
      SKIP_ONEFILE_BUILD: "1"
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp
      - ~/yt-dlp-build-venv:/yt-dlp-build-venv

  linux_armv7l_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/arm/v7"
      args:
        IMAGE: arm32v7/debian:bullseye
    environment:
      EXE_NAME: ${EXE_NAME}
      TEST_ONEDIR_BUILD: "1"
    volumes:
      - ~/build:/build

  musllinux_x86_64:
    build:
      context: linux
      platforms:
        - "linux/amd64"
      args:
        BASEIMAGE: ghcr.io/yt-dlp/musllinux_1_2_x86_64-shared:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  musllinux_x86_64_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/amd64"
      args:
        IMAGE: alpine:3.22
    environment:
      EXE_NAME: ${EXE_NAME}
      SKIP_UPDATE_TO: "1"  # TODO: remove when there is a musllinux_aarch64 release to --update-to
    volumes:
      - ~/build:/build

  musllinux_aarch64:
    build:
      context: linux
      platforms:
        - "linux/arm64"
      args:
        BASEIMAGE: ghcr.io/yt-dlp/musllinux_1_2_aarch64-shared:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
      EXCLUDE_CURL_CFFI: "1"
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  musllinux_aarch64_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/arm64"
      args:
        IMAGE: alpine:3.22
    environment:
      EXE_NAME: ${EXE_NAME}
      SKIP_UPDATE_TO: "1"  # TODO: remove when there is a musllinux_aarch64 release to --update-to
    volumes:
      - ~/build:/build
