services:

  linux_x86_64:
    build:
      context: linux
      platforms:
        - "linux/amd64"
      args:
        BASEIMAGE: ghcr.io/bashonly/manylinux2014_x86_64_builds:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  linux_aarch64:
    build:
      context: linux
      platforms:
        - "linux/arm64"
      args:
        BASEIMAGE: ghcr.io/bashonly/manylinux2014_aarch64_builds:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  linux_armv7l:
    build:
      context: linux
      platforms:
        - "linux/arm/v7"
      args:
        BASEIMAGE: ghcr.io/bashonly/manylinux_2_31_armv7l_builds:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
      SKIP_ONEDIR_BUILD: "1"
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  linux_armv7l_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/arm/v7"
      args:
        IMAGE: arm32v7/debian:bullseye
    environment:
      EXE_NAME: ${EXE_NAME}
    volumes:
      - ~/build:/build

  musllinux_x86_64:
    build:
      context: linux
      platforms:
        - "linux/amd64"
      args:
        BASEIMAGE: ghcr.io/bashonly/musllinux_1_2_x86_64_builds:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  musllinux_x86_64_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/amd64"
      args:
        IMAGE: alpine:3.22
    environment:
      EXE_NAME: ${EXE_NAME}
      SKIP_UPDATE_TO: "1"
    volumes:
      - ~/build:/build

  musllinux_aarch64:
    build:
      context: linux
      platforms:
        - "linux/arm64"
      args:
        BASEIMAGE: ghcr.io/bashonly/musllinux_1_2_aarch64_builds:latest
    environment:
      EXE_NAME: ${EXE_NAME}
      CHANNEL: ${CHANNEL}
      ORIGIN: ${ORIGIN}
      VERSION: ${VERSION}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp

  musllinux_aarch64_verify:
    build:
      context: linux
      dockerfile: verify.Dockerfile
      platforms:
        - "linux/arm64"
      args:
        IMAGE: alpine:3.22
    environment:
      EXE_NAME: ${EXE_NAME}
      SKIP_UPDATE_TO: "1"
    volumes:
      - ~/build:/build
