services:
  linux:
    build: linux
    environment:
      channel: ${channel}
      origin: ${origin}
      version: ${version}
      BASEIMAGE: ${BASEIMAGE}
    volumes:
      - ~/build:/build
      - ../..:/yt-dlp
