name: Release
on:
  workflow_call:
    inputs:
      source:
        required: false
        default: ''
        type: string
      target:
        required: false
        default: ''
        type: string
      version:
        required: false
        default: ''
        type: string
      linux_armv7l:
        required: false
        default: false
        type: boolean
      prerelease:
        required: false
        default: true
        type: boolean
  workflow_dispatch:
    inputs:
      source:
        description: |
          SOURCE of this release's updates:
          channel, repo, tag, or channel/repo@tag
          (default: <current_repo>)
        required: false
        default: ''
        type: string
      target:
        description: |
          TARGET to publish this release to:
          channel, tag, or channel@tag
          (default: <source> if writable else <current_repo>[@source_tag])
        required: false
        default: ''
        type: string
      version:
        description: |
          VERSION: yyyy.mm.dd[.rev] or rev
          (default: auto-generated)
        required: false
        default: ''
        type: string
      linux_armv7l:
        description: Include linux_armv7l
        default: true
        type: boolean
      prerelease:
        description: Pre-release
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  prepare:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.setup_variables.outputs.channel }}
      version: ${{ steps.setup_variables.outputs.version }}
      target_repo: ${{ steps.setup_variables.outputs.target_repo }}
      target_repo_token: ${{ steps.setup_variables.outputs.target_repo_token }}
      target_tag: ${{ steps.setup_variables.outputs.target_tag }}
      pypi_project: ${{ steps.setup_variables.outputs.pypi_project }}
      pypi_suffix: ${{ steps.setup_variables.outputs.pypi_suffix }}
      head_sha: ${{ steps.get_target.outputs.head_sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Process inputs
        id: process_inputs
        env:
          INPUTS: ${{ toJSON(inputs) }}
        shell: python
        run: |
          import json
          import os
          inputs = json.loads(os.environ['INPUTS'])
          print('::group::Inputs')
          print(json.dumps(inputs, indent=2))
          print('::endgroup::')
          outputs = {}
          for key in ('source', 'target'):
              repo, _, tag = inputs[key].partition('@')
              outputs[f'{key}_repo'] = repo
              outputs[f'{key}_tag'] = tag
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write('\n'.join(f'{key}={value}' for key, value in outputs.items()))

      - name: Setup variables
        id: setup_variables
        env:
          INPUTS: ${{ toJSON(inputs) }}
          PROCESSED: ${{ toJSON(steps.process_inputs.outputs) }}
          SOURCE_REPO: ${{ steps.process_inputs.outputs.source_repo }}
          TARGET_REPO: ${{ steps.process_inputs.outputs.target_repo }}
          REPOSITORY: ${{ github.repository }}
          PUSH_VERSION_COMMIT: ${{ vars.PUSH_VERSION_COMMIT }}
          PYPI_PROJECT: ${{ vars.PYPI_PROJECT }}
          SOURCE_PYPI_PROJECT: ${{ vars[format('{0}_pypi_project', steps.process_inputs.outputs.source_repo)] }}
          SOURCE_PYPI_SUFFIX: ${{ vars[format('{0}_pypi_suffix', steps.process_inputs.outputs.source_repo)] }}
          TARGET_PYPI_PROJECT: ${{ vars[format('{0}_pypi_project', steps.process_inputs.outputs.target_repo)] }}
          TARGET_PYPI_SUFFIX: ${{ vars[format('{0}_pypi_suffix', steps.process_inputs.outputs.target_repo)] }}
          SOURCE_ARCHIVE_REPO: ${{ vars[format('{0}_archive_repo', steps.process_inputs.outputs.source_repo)] }}
          TARGET_ARCHIVE_REPO: ${{ vars[format('{0}_archive_repo', steps.process_inputs.outputs.target_repo)] }}
          HAS_SOURCE_ARCHIVE_REPO_TOKEN: ${{ toJSON(!!secrets[format('{0}_archive_repo_token', steps.process_inputs.outputs.source_repo)])}}
          HAS_TARGET_ARCHIVE_REPO_TOKEN: ${{ toJSON(!!secrets[format('{0}_archive_repo_token', steps.process_inputs.outputs.target_repo)])}}
          HAS_ARCHIVE_REPO_TOKEN: ${{ toJSON(!!secrets.ARCHIVE_REPO_TOKEN) }}
        shell: python
        run: |
          import datetime
          import json
          import os
          import subprocess
          import sys
          
          
          def fallback_token(token_name):
              if not json.loads(os.environ['HAS_ARCHIVE_REPO_TOKEN']):
                  print('::error::Repository access secret {token_name.upper()} not found')
                  sys.exit(1)
              return 'ARCHIVE_REPO_TOKEN'
          
          
          REPOSITORY = os.environ['INPUTS']
          inputs = json.loads(os.environ['INPUTS'])
          processed = json.loads(os.environ['PROCESSED'])
          
          source_channel = None
          target_repo_token = None
          pypi_project = None
          pypi_suffix = None
          
          source_repo = processed['source_repo']
          source_tag = processed['source_tag']
          if source_repo == 'stable':
              source_repo = 'yt-dlp/yt-dlp'
          elif not source_repo:
              source_repo = REPOSITORY
          elif os.environ['SOURCE_ARCHIVE_REPO']:
              source_channel = os.environ['SOURCE_ARCHIVE_REPO']
          elif not source_tag and '/' not in source_repo:
              source_tag = source_repo
              source_repo = REPOSITORY
          
          resolved_source = source_repo
          if source_tag:
              resolved_source = f'{resolved_source}@{source_tag}'
          elif source_repo == 'yt-dlp/yt-dlp':
              resolved_source = 'stable'
          
          if inputs['prerelease'] or not os.environ['PUSH_VERSION_COMMIT']:
              revision = datetime.datetime.now(tz=datetime.timezone.utc).strftime('%H%M%S')
          else:
              revision = ''
          
          version = json.loads(subprocess.run((
              'python', 'devscripts/update-version.py', '--json',
              '-c', resolved_source,
              '-r', REPOSITORY,
              inputs['version'] or revision,
          ), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout)['version']
          
          target_repo = processed['target_repo']
          target_tag = processed['target_tag']
          if target_repo:
              if not target_tag:
                  if os.environ['TARGET_ARCHIVE_REPO']:
                      target_tag = source_tag or version
                  else:
                      target_tag = target_repo
                      target_repo = REPOSITORY
              if target_repo != REPOSITORY:
                  target_repo = os.environ['TARGET_ARCHIVE_REPO']
                  target_repo_token = f'{processed["target_repo"]}_archive_repo_token'
                  if not json.loads(os.environ['HAS_TARGET_ARCHIVE_REPO_TOKEN']):
                      target_repo_token = fallback_token(target_repo_token)
                  pypi_project = os.environ['TARGET_PYPI_PROJECT']
                  pypi_suffix = os.environ['TARGET_PYPI_SUFFIX']
          else:
              target_tag = source_tag or version
              if source_channel:
                  target_repo = source_channel
                  target_repo_token = f'{processed["source_repo"]}_archive_repo_token'
                  if not json.loads(os.environ['HAS_SOURCE_ARCHIVE_REPO_TOKEN']):
                      target_repo_token = fallback_token(target_repo_token)
                  pypi_project = os.environ['SOURCE_PYPI_PROJECT']
                  pypi_suffix = os.environ['SOURCE_PYPI_SUFFIX']
              else:
                  target_repo = REPOSITORY
          
          if target_repo == REPOSITORY and inputs['prerelease']:
              pypi_project = os.environ['PYPI_PROJECT']
          
          outputs = {
              'channel': resolved_source,
              'version': version,
              'target_repo': target_repo,
              'target_repo_token': target_repo_token,
              'target_tag': target_tag,
              'pypi_project': pypi_project,
              'pypi_suffix': pypi_suffix,
          }
          print('::group::Output variables')
          print(json.dumps(outputs, indent=2))
          print('::endgroup::')
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write('\n'.join(f'{key}={value or ""}' for key, value in outputs.items()))

      - name: Update documentation
        env:
          version: ${{ steps.setup_variables.outputs.version }}
          target_repo: ${{ steps.setup_variables.outputs.target_repo }}
        if: |
          !inputs.prerelease && env.target_repo == github.repository
        run: |
          python devscripts/update_changelog.py -vv
          make doc

      - name: Push to release
        id: push_release
        env:
          version: ${{ steps.setup_variables.outputs.version }}
          target_repo: ${{ steps.setup_variables.outputs.target_repo }}
        if: |
          !inputs.prerelease && env.target_repo == github.repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Release ${{ env.version }}" \
            -m "Created by: ${{ github.event.sender.login }}" -m ":ci skip all"
          git push origin --force ${{ github.event.ref }}:release

      - name: Get target commitish
        id: get_target
        run: |
          echo "head_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Update master
        env:
          target_repo: ${{ steps.setup_variables.outputs.target_repo }}
        if: |
          vars.PUSH_VERSION_COMMIT != '' && !inputs.prerelease && env.target_repo == github.repository
        run: git push origin ${{ github.event.ref }}

  build:
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.prepare.outputs.version }}
      channel: ${{ needs.prepare.outputs.channel }}
      origin: ${{ needs.prepare.outputs.target_repo }}
      linux_armv7l: ${{ inputs.linux_armv7l }}
    permissions:
      contents: read
    secrets:
      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

  publish_pypi:
    needs: [prepare, build]
    if: ${{ needs.prepare.outputs.pypi_project }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Requirements
        run: |
          sudo apt -y install pandoc man
          python devscripts/install_deps.py -o --include build

      - name: Prepare
        env:
          version: ${{ needs.prepare.outputs.version }}
          suffix: ${{ needs.prepare.outputs.pypi_suffix }}
          channel: ${{ needs.prepare.outputs.channel }}
          target_repo: ${{ needs.prepare.outputs.target_repo }}
          pypi_project: ${{ needs.prepare.outputs.pypi_project }}
        run: |
          python devscripts/update-version.py -c "${{ env.channel }}" -r "${{ env.target_repo }}" -s "${{ env.suffix }}" "${{ env.version }}"
          python devscripts/update_changelog.py -vv
          python devscripts/make_lazy_extractors.py
          sed -i -E '0,/(name = ")[^"]+(")/s//\1${{ env.pypi_project }}\2/' pyproject.toml

      - name: Build
        run: |
          rm -rf dist/*
          make pypi-files
          printf '%s\n\n' \
            'Official repository: <https://github.com/yt-dlp/yt-dlp>' \
            '**PS**: Some links in this document will not work since this is a copy of the README.md from Github' > ./README.md.new
          cat ./README.md >> ./README.md.new && mv -f ./README.md.new ./README.md
          python devscripts/set-variant.py pip -M "You installed yt-dlp with pip or using the wheel from PyPi; Use that to update"
          make clean-cache
          python -m build --no-isolation .

      - name: Upload artifacts
        if: github.event_name != 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: build-pypi
          path: |
            dist/*
          compression-level: 0

      - name: Publish to PyPI
        if: github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  publish:
    needs: [prepare, build]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: artifact
          pattern: build-*
          merge-multiple: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Generate release notes
        env:
          head_sha: ${{ needs.prepare.outputs.head_sha }}
          target_repo: ${{ needs.prepare.outputs.target_repo }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}
        run: |
          printf '%s' \
            '[![Installation](https://img.shields.io/badge/-Which%20file%20to%20download%3F-white.svg?style=for-the-badge)]' \
              '(https://github.com/${{ github.repository }}#installation "Installation instructions") ' \
            '[![Discord](https://img.shields.io/discord/807245652072857610?color=blue&labelColor=555555&label=&logo=discord&style=for-the-badge)]' \
              '(https://discord.gg/H5MNcFW63r "Discord") ' \
            '[![Donate](https://img.shields.io/badge/_-Donate-red.svg?logo=githubsponsors&labelColor=555555&style=for-the-badge)]' \
              '(https://github.com/yt-dlp/yt-dlp/blob/master/Collaborators.md#collaborators "Donate") ' \
            '[![Documentation](https://img.shields.io/badge/-Docs-brightgreen.svg?style=for-the-badge&logo=GitBook&labelColor=555555)]' \
              '(https://github.com/${{ github.repository }}' \
              '${{ env.target_repo == github.repository && format('/tree/{0}', env.target_tag) || '' }}#readme "Documentation") ' \
            ${{ env.target_repo == 'yt-dlp/yt-dlp' && '\
              "[![Nightly](https://img.shields.io/badge/Nightly%20builds-purple.svg?style=for-the-badge)]" \
              "(https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest \"Nightly builds\") " \
              "[![Master](https://img.shields.io/badge/Master%20builds-lightblue.svg?style=for-the-badge)]" \
              "(https://github.com/yt-dlp/yt-dlp-master-builds/releases/latest \"Master builds\")"' || '' }} > ./RELEASE_NOTES
          printf '\n\n' >> ./RELEASE_NOTES
          cat >> ./RELEASE_NOTES << EOF
          #### A description of the various files is in the [README](https://github.com/${{ github.repository }}#release-files)
          ---
          $(python ./devscripts/make_changelog.py -vv --collapsible)
          EOF
          printf '%s\n\n' '**This is a pre-release build**' >> ./PRERELEASE_NOTES
          cat ./RELEASE_NOTES >> ./PRERELEASE_NOTES
          printf '%s\n\n' 'Generated from: https://github.com/${{ github.repository }}/commit/${{ env.head_sha }}' >> ./ARCHIVE_NOTES
          cat ./RELEASE_NOTES >> ./ARCHIVE_NOTES

      - name: Publish to archive repo
        env:
          GH_TOKEN: ${{ secrets[needs.prepare.outputs.target_repo_token] }}
          GH_REPO: ${{ needs.prepare.outputs.target_repo }}
          version: ${{ needs.prepare.outputs.version }}
          channel: ${{ needs.prepare.outputs.channel }}
        if: |
          inputs.prerelease && env.GH_TOKEN != '' && env.GH_REPO != '' && env.GH_REPO != github.repository
        run: |
          title="${{ startswith(env.GH_REPO, 'yt-dlp/') && 'yt-dlp ' || '' }}${{ env.channel }}"
          gh release create \
            --notes-file ARCHIVE_NOTES \
            --title "${title} ${{ env.version }}" \
            ${{ env.version }} \
            artifact/*

      - name: Prune old release
        env:
          GH_TOKEN: ${{ github.token }}
          version: ${{ needs.prepare.outputs.version }}
          target_repo: ${{ needs.prepare.outputs.target_repo }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}
        if: |
          env.target_repo == github.repository && env.target_tag != env.version
        run: |
          gh release delete --yes --cleanup-tag "${{ env.target_tag }}" || true
          git tag --delete "${{ env.target_tag }}" || true
          sleep 5  # Enough time to cover deletion race condition

      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          version: ${{ needs.prepare.outputs.version }}
          target_repo: ${{ needs.prepare.outputs.target_repo }}
          target_tag: ${{ needs.prepare.outputs.target_tag }}
          head_sha: ${{ needs.prepare.outputs.head_sha }}
        if: |
          env.target_repo == github.repository
        run: |
          title="${{ github.repository == 'yt-dlp/yt-dlp' && 'yt-dlp ' || '' }}"
          title+="${{ env.target_tag != env.version && format('{0} ', env.target_tag) || '' }}"
          gh release create \
            --notes-file ${{ inputs.prerelease && 'PRERELEASE_NOTES' || 'RELEASE_NOTES' }} \
            --target ${{ env.head_sha }} \
            --title "${title}${{ env.version }}" \
            ${{ inputs.prerelease && '--prerelease' || '' }} \
            ${{ env.target_tag }} \
            artifact/*
